Fixed 3

diff --git a/.github/workflows/thirteenth_workflow.yml b/.github/workflows/thirteenth_workflow.yml
--- a/.github/workflows/thirteenth_workflow.yml
+++ b/.github/workflows/thirteenth_workflow.yml
@@ -5,6 +5,9 @@ jobs:
   job:
     runs-on: ubuntu-latest
     steps:
+      - name: Failure Step
+        id: error-step
+        run: exit 1
       - name: Runs on Canceled
         if: ${{ cancelled() }}
         run: echo "Runs on Canceled"
@@ -15,7 +18,7 @@ jobs:
         if: ${{ success() }}
         run: echo "Runs on Success"
       - name: Runs on Failure
-        if: ${{ failure() }}
+        if: ${{ failure() && steps.error-step.conclusion == 'failure' }}
         run: echo "Runs on Failur"
   second-job:
     runs-on: ubuntu-latest
